// Created by iWeb 3.0.4 local-build-20140325

function writeMovie1()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id1" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="120" height="16" style="height: 16px; left: 518px; position: absolute; top: 1222px; width: 120px; z-index: 1; "><param name="src" value="Media/03%20Manga%20el%20Banjo-1.mp3" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id1" type="video/quicktime" width="120" height="16" style="height: 16px; left: 518px; position: absolute; top: 1222px; width: 120px; z-index: 1; "><param name="src" value="Media/03%20Manga%20el%20Banjo-1.mp3"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id1" type="video/quicktime" width="120" height="16" data="Media/03%20Manga%20el%20Banjo-1.mp3" style="height: 16px; left: 518px; position: absolute; top: 1222px; width: 120px; z-index: 1; "><param name="src" value="Media/03%20Manga%20el%20Banjo-1.mp3"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie2()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id2" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="120" height="16" style="height: 16px; left: 528px; position: absolute; top: 1841px; width: 120px; z-index: 1; "><param name="src" value="Media/08%20Stop.mp3" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id2" type="video/quicktime" width="120" height="16" style="height: 16px; left: 528px; position: absolute; top: 1841px; width: 120px; z-index: 1; "><param name="src" value="Media/08%20Stop.mp3"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id2" type="video/quicktime" width="120" height="16" data="Media/08%20Stop.mp3" style="height: 16px; left: 528px; position: absolute; top: 1841px; width: 120px; z-index: 1; "><param name="src" value="Media/08%20Stop.mp3"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie3()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id8" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="121" height="16" style="height: 16px; left: 520px; position: absolute; top: 1534px; width: 121px; z-index: 1; "><param name="src" value="Media/BarcelonaBluegrassBand-Bel%27s%20Jam.mp3" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id8" type="video/quicktime" width="121" height="16" style="height: 16px; left: 520px; position: absolute; top: 1534px; width: 121px; z-index: 1; "><param name="src" value="Media/BarcelonaBluegrassBand-Bel%27s%20Jam.mp3"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id8" type="video/quicktime" width="121" height="16" data="Media/BarcelonaBluegrassBand-Bel%27s%20Jam.mp3" style="height: 16px; left: 520px; position: absolute; top: 1534px; width: 121px; z-index: 1; "><param name="src" value="Media/BarcelonaBluegrassBand-Bel%27s%20Jam.mp3"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie4()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id9" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="121" height="16" style="height: 16px; left: 518px; position: absolute; top: 917px; width: 121px; z-index: 1; "><param name="src" value="Media/Swin4%2042%20De%CC%81boucher.mp3" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id9" type="video/quicktime" width="121" height="16" style="height: 16px; left: 518px; position: absolute; top: 917px; width: 121px; z-index: 1; "><param name="src" value="Media/Swin4%2042%20De%CC%81boucher.mp3"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id9" type="video/quicktime" width="121" height="16" data="Media/Swin4%2042%20De%CC%81boucher.mp3" style="height: 16px; left: 518px; position: absolute; top: 917px; width: 121px; z-index: 1; "><param name="src" value="Media/Swin4%2042%20De%CC%81boucher.mp3"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie5()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id17" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="121" height="16" style="height: 16px; left: 517px; position: absolute; top: 590px; width: 121px; z-index: 1; "><param name="src" value="Media/04%20Caraman.mp3" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id17" type="video/quicktime" width="121" height="16" style="height: 16px; left: 517px; position: absolute; top: 590px; width: 121px; z-index: 1; "><param name="src" value="Media/04%20Caraman.mp3"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id17" type="video/quicktime" width="121" height="16" data="Media/04%20Caraman.mp3" style="height: 16px; left: 517px; position: absolute; top: 590px; width: 121px; z-index: 1; "><param name="src" value="Media/04%20Caraman.mp3"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_8:new IWShadow({blurRadius:10,offset:new IWPoint(2.1213,2.1213),color:'#000000',opacity:0.750000}),shadow_4:new IWShadow({blurRadius:10,offset:new IWPoint(2.1213,2.1213),color:'#000000',opacity:0.750000}),shadow_9:new IWShadow({blurRadius:10,offset:new IWPoint(2.1213,2.1213),color:'#000000',opacity:0.750000}),shadow_10:new IWShadow({blurRadius:10,offset:new IWPoint(2.1213,2.1213),color:'#000000',opacity:0.750000}),shadow_0:new IWShadow({blurRadius:10,offset:new IWPoint(2.1213,2.1213),color:'#000000',opacity:0.750000}),shadow_1:new IWShadow({blurRadius:10,offset:new IWPoint(2.1213,2.1213),color:'#000000',opacity:0.750000}),shadow_5:new IWShadow({blurRadius:10,offset:new IWPoint(2.1213,2.1213),color:'#000000',opacity:0.750000}),shadow_6:new IWShadow({blurRadius:10,offset:new IWPoint(2.1213,2.1213),color:'#000000',opacity:0.750000}),shadow_3:new IWShadow({blurRadius:10,offset:new IWPoint(2.1213,2.1213),color:'#000000',opacity:0.750000}),shadow_2:new IWShadow({blurRadius:10,offset:new IWPoint(2.8284,2.8284),color:'#000000',opacity:0.750000}),shadow_7:new IWShadow({blurRadius:10,offset:new IWPoint(2.1213,2.1213),color:'#000000',opacity:0.750000})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Tienda_files/TiendaMoz.css')
adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id3');fixupIECSS3Opacity('id4');fixupIECSS3Opacity('id5');fixupIECSS3Opacity('id6');fixupIECSS3Opacity('id10');fixupIECSS3Opacity('id11');fixupIECSS3Opacity('id12');applyEffects()}
